name: tomcat
version: 8.5.5
summary: A Java Servlet and Java Server Pages container
description: A Java Servlet and Java Server Pages container developed under the Apache License
confinement: strict

parts:
  tomcat:
    plugin: ant
    source: https://svn.apache.org/repos/asf/tomcat/tc8.5.x/trunk/
    source-type: svn
    prepare: |
      cp build.properties.default build.properties
    install: |
      cp -r output/build/* $SNAPCRAFT_PART_INSTALL
      cat <<EOF > $SNAPCRAFT_PART_INSTALL/tomcat-launch
      #!/bin/sh
      export JRE_HOME=\${SNAP}/usr/lib/jvm/default-java/jre
      export JAVA_HOME=\${SNAP}/usr/lib/jvm/default-java/jre
      export CATALINA_HOME=\${SNAP}
      export CATALINA_BASE=\${SNAP_DATA}
      export CATALINA_TMPDIR=/tmp
      cp -rn \${CATALINA_HOME}/conf \${CATALINA_BASE}/
      cp -rn \${CATALINA_HOME}/webapps \${CATALINA_BASE}/
      exec \${CATALINA_HOME}/bin/catalina.sh run
      EOF
      chmod +x $SNAPCRAFT_PART_INSTALL/tomcat-launch
