#!/bin/sh

export JRE_HOME=${SNAP}/usr/lib/jvm/default-java/jre
export JAVA_HOME=${SNAP}/usr/lib/jvm/default-java/jre

export CATALINA_HOME=${SNAP}
export CATALINA_BASE=${SNAP_DATA}
export CATALINA_TMPDIR=/tmp

mkdir -p ${CATALINA_BASE}/conf/
cp -n ${CATALINA_HOME}/conf/* ${CATALINA_BASE}/conf/

exec ${CATALINA_HOME}/bin/catalina.sh run
